name: check

on:
  workflow_dispatch

jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }})
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, r: 'release' }
          - { os: windows-latest, r: 'release' }
          - { os: macos-latest, r: 'release' }

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
          needs: check

      - name: Check
        uses: r-lib/actions/check-r-package@v2
        with:
          cran: false
